# Generated by Django 2.1.7 on 2019-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=200)),
                ('food_content', models.TextField()),
                ('food_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
